// @ts-nocheck
/* eslint-disable */
// --------------------------------------------------
// This file is auto-generated by Tuyau. Do not edit manually !
// --------------------------------------------------

import type { MakeTuyauRequest, MakeTuyauResponse } from '@tuyau/utils/types'
import type { InferInput } from '@vinejs/vine/types'

type ApiV1UsersPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/user_validator.ts')['createUserValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/users_controller.ts').default['create'], true>
}
type ApiV1UsersLoginPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/user_validator.ts')['loginValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/users_controller.ts').default['apiLogin'], true>
}
type ApiV1UsersMeGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/users_controller.ts').default['me'], false>
}
type ApiV1UsersIdPut = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/user_validator.ts')['updateUserValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/users_controller.ts').default['update'], true>
}
type ApiV1UsersIdDelete = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/users_controller.ts').default['delete'], false>
}
type ApiV1CustomersAllGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/customers_controller.ts').default['getAll'], false>
}
type ApiV1CustomersStatsGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/customers_controller.ts').default['stats'], false>
}
type ApiV1CustomersPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/customer_validator.ts')['createCustomerValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/customers_controller.ts').default['createCustomer'], true>
}
type ApiV1CustomersIdGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/customers_controller.ts').default['getCustomer'], false>
}
type ApiV1CustomersIdPut = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/customer_validator.ts')['updateCustomerValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/customers_controller.ts').default['update'], true>
}
type ApiV1CustomersIdDelete = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/customers_controller.ts').default['delete'], false>
}
type ApiV1JobsDashboardGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/jobs_controller.ts').default['dashboard'], false>
}
type ApiV1JobsPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/job_validator.ts')['createJobValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/jobs_controller.ts').default['createJob'], true>
}
type ApiV1JobsGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/jobs_controller.ts').default['getAll'], false>
}
type ApiV1JobsIdPut = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/job_validator.ts')['updateJobValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/jobs_controller.ts').default['update'], true>
}
type ApiV1JobsIdDelete = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/jobs_controller.ts').default['delete'], false>
}
type ApiV1PaymentsPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/payment_validator.ts')['createPaymentValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/payments_controller.ts').default['createPayment'], true>
}
type ApiV1PaymentsGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/payments_controller.ts').default['getAll'], false>
}
type ApiV1PaymentsIdPut = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/payment_validator.ts')['updatePaymentValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/payments_controller.ts').default['updatePayment'], true>
}
type ApiV1PaymentsIdDelete = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/payments_controller.ts').default['delete'], false>
}
type ApiV1InvoicesPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/invoice_validator.ts')['createInvoiceValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/invoices_controller.ts').default['createInvoice'], true>
}
type ApiV1InvoicesGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/invoices_controller.ts').default['getAll'], false>
}
type ApiV1InvoicesIdPut = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/invoice_validator.ts')['updateInvoiceValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/invoices_controller.ts').default['update'], true>
}
type ApiV1InvoicesIdDelete = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/invoices_controller.ts').default['delete'], false>
}
type ApiV1HealthGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/health_checks_controller.ts').default['handle'], false>
}
export interface ApiDefinition {
  'api': {
    'v1': {
      'users': {
        '$url': {
        };
        '$post': ApiV1UsersPost;
        'login': {
          '$url': {
          };
          '$post': ApiV1UsersLoginPost;
        };
        'me': {
          '$url': {
          };
          '$get': ApiV1UsersMeGetHead;
          '$head': ApiV1UsersMeGetHead;
        };
        ':id': {
          '$url': {
          };
          '$put': ApiV1UsersIdPut;
          '$delete': ApiV1UsersIdDelete;
        };
      };
      'customers': {
        'all': {
          '$url': {
          };
          '$get': ApiV1CustomersAllGetHead;
          '$head': ApiV1CustomersAllGetHead;
        };
        'stats': {
          '$url': {
          };
          '$get': ApiV1CustomersStatsGetHead;
          '$head': ApiV1CustomersStatsGetHead;
        };
        '$url': {
        };
        '$post': ApiV1CustomersPost;
        ':id': {
          '$url': {
          };
          '$get': ApiV1CustomersIdGetHead;
          '$head': ApiV1CustomersIdGetHead;
          '$put': ApiV1CustomersIdPut;
          '$delete': ApiV1CustomersIdDelete;
        };
      };
      'jobs': {
        'dashboard': {
          '$url': {
          };
          '$get': ApiV1JobsDashboardGetHead;
          '$head': ApiV1JobsDashboardGetHead;
        };
        '$url': {
        };
        '$post': ApiV1JobsPost;
        '$get': ApiV1JobsGetHead;
        '$head': ApiV1JobsGetHead;
        ':id': {
          '$url': {
          };
          '$put': ApiV1JobsIdPut;
          '$delete': ApiV1JobsIdDelete;
        };
      };
      'payments': {
        '$url': {
        };
        '$post': ApiV1PaymentsPost;
        '$get': ApiV1PaymentsGetHead;
        '$head': ApiV1PaymentsGetHead;
        ':id': {
          '$url': {
          };
          '$put': ApiV1PaymentsIdPut;
          '$delete': ApiV1PaymentsIdDelete;
        };
      };
      'invoices': {
        '$url': {
        };
        '$post': ApiV1InvoicesPost;
        '$get': ApiV1InvoicesGetHead;
        '$head': ApiV1InvoicesGetHead;
        ':id': {
          '$url': {
          };
          '$put': ApiV1InvoicesIdPut;
          '$delete': ApiV1InvoicesIdDelete;
        };
      };
      'health': {
        '$url': {
        };
        '$get': ApiV1HealthGetHead;
        '$head': ApiV1HealthGetHead;
      };
    };
  };
}
const routes = [
] as const;
export const api = {
  routes,
  definition: {} as ApiDefinition
}
declare module '@tuyau/inertia/types' {
  type InertiaApi = typeof api
  export interface Api extends InertiaApi {}
}
